# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b9efdc014c9cf7f2bdebbdcbd520bd509874ebac20937d54d6ddcbfedf1a724d6296e6c040dca37289853ee22ec4e2b18de1e3b4de99930745df54da1a87803

test:
  secret_key_base: a618f5d66cad41c899855e9de432cc71c3f3c7af2d0a7ef32658280cf66b59a4b3c8faadce96f35a4e4b6486a425f98dedf596070f9af8c7a2268a35f6ef02fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
